spring.application.name=studysessiontracker

spring.datasource.url=jdbc:mysql://localhost:3306/study_session_tracker
spring.datasource.username=ssta_app
spring.datasource.password=ProjectsBuilding00@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
